name: interlocution_ui
description: "Interlocution UI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0-26.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  chat_bubbles: ^1.6.0
  go_router: ^14.2.3
  dio: ^5.6.0
  url_strategy: ^0.3.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.prod
    - assets/config.dev
    - assets/github.png
